[programs.localnet]
arb_program = "AF5rgAiHHSQWctDDuesV8q3fRYBUgj8ZLKYqg8dkSNmR"

[programs.devnet]
arb_program = "AF5rgAiHHSQWctDDuesV8q3fRYBUgj8ZLKYqg8dkSNmR"

[programs.mainnet]
arb_program = "AF5rgAiHHSQWctDDuesV8q3fRYBUgj8ZLKYqg8dkSNmR"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
deploy = "anchor build && anchor deploy"
test = "anchor test --skip-local-validator"

[workspace]
members = [
  "programs/arb_program"
]

[features]
localnet = []
devnet = []
mainnet = []
