[programs.devnet]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc" # Program ID en Devnet

[programs.mainnet]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc" # Program ID en Mainnet

[programs.localtest]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc" # Program ID en entorno local

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
deploy = "anchor build && anchor deploy"
test = "anchor test --skip-local-validator" # Pruebas sin usar el validador local
localtest = "solana-test-validator --reset && anchor build && anchor deploy --provider.cluster http://127.0.0.1:8899 && anchor test" # Script para pruebas locales

[workspace]
members = [
  "programs/arb_program"
]

[features]
devnet = []
mainnet = []
localtest = []
