[programs.localnet]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc"

[programs.devnet]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc"

[programs.mainnet]
arb_program = "3XaaffPKycGUe2yc5EC2yGwyFugDUWH6FY9X97YuG5Xc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
deploy = "anchor build && anchor deploy"
test = "anchor test --skip-local-validator"

[workspace]
members = [
  "programs/arb_program"
]

[features]
localnet = []
devnet = []
mainnet = []
