[package]
name = "dex_swap_example"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
solana-program = "1.16.5"

[features]
no-entrypoint = []

[profile.release]
overflow-checks = true
