[package]
name = "arb_program"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.16.11"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = [] 